spring:
  application:
    name: pp-3-1-1

  datasource:
    url: "jdbc:h2:mem:users"
    driver-class-name: org.h2.Driver
    username: "sa"

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
